import React, { useEffect, useMemo, useRef, useState } from "react";
import { StyleSheet } from "react-native";
import MapView, { Marker } from "react-native-maps";

import { PLACE_TYPE_LABELS, Place } from "@/data/places";
import { useTheme } from "@/context/ThemeContext";
import { formatDistance } from "@/lib/distance";
import {
  assignSlots,
  buildPinGroups,
  type MapRegion,
  type PinCandidate,
  type PinCluster,
  type Slot,
} from "@/lib/mapPins";

// Google's own POI markers are drawn LARGER and bolder than this app's place
// dots, in the same colour language the map legend claims for place types — so
// a purple "entertainment" pin beside a legend saying purple = Multi-faith
// reads as one of the app's places, and tapping it does nothing. There is no
// prop for this; suppressing the POI label layer (icon AND text) through the
// map style is the only way to stop the base map impersonating the data.
//
// Park names come back afterwards: `labels.text` without `labels.icon` is a
// name with no pin, which is orientation rather than a competing marker.
// Transit is a separate featureType and is untouched for the same reason.
const NO_POI_STYLE = [
  {
    featureType: "poi",
    elementType: "labels",
    stylers: [{ visibility: "off" }],
  },
  {
    featureType: "poi.park",
    elementType: "labels.text",
    stylers: [{ visibility: "on" }],
  },
];

// Google Maps (Android) needs an explicit style array for dark mode; Apple
// Maps (iOS) follows the userInterfaceStyle prop instead and ignores this.
//
// Lifted a couple of steps out of Google's stock night palette, which sits at
// roughly 18% lightness and reads as a black hole beside the sheet rather than
// as a map — streets you cannot follow and water you cannot tell from land.
// These are deliberately NOT theme tokens: this is Google's basemap
// vocabulary, not the app's surfaces, and the app's own markers and the blue
// location dot have to stay legible on top of it. Still firmly a night style —
// every value here is far below the light basemap — just readable.
//
// Land sits below the sheet's own #1E1E1C so the map still reads as the
// outside; roads and labels carry most of the lift, since they are what
// someone is actually trying to read.
const DARK_MAP_STYLE = [
  { elementType: "geometry", stylers: [{ color: "#333f52" }] },
  { elementType: "labels.text.fill", stylers: [{ color: "#aab4c4" }] },
  { elementType: "labels.text.stroke", stylers: [{ color: "#333f52" }] },
  {
    featureType: "poi",
    elementType: "labels.text.fill",
    stylers: [{ color: "#a99a95" }],
  },
  {
    featureType: "road",
    elementType: "geometry",
    stylers: [{ color: "#4a5566" }],
  },
  {
    featureType: "road",
    elementType: "geometry.stroke",
    stylers: [{ color: "#3a4353" }],
  },
  {
    featureType: "road",
    elementType: "labels.text.fill",
    stylers: [{ color: "#b8c0cc" }],
  },
  {
    featureType: "transit",
    elementType: "geometry",
    stylers: [{ color: "#414c5e" }],
  },
  {
    featureType: "water",
    elementType: "geometry",
    stylers: [{ color: "#22354f" }],
  },
  // Last, so the visibility rules win over the poi text colour above.
  ...NO_POI_STYLE,
];

const FALLBACK_REGION = {
  latitude: 51.5074,
  longitude: -0.1278,
  latitudeDelta: 0.05,
  longitudeDelta: 0.05,
};

// Where unused pool markers park: a valid coordinate in the Gulf of Guinea,
// far outside UK/Ireland coverage, rendered at opacity 0.
const HIDDEN_COORDINATE = { latitude: 0, longitude: 0 };

// Small pre-rendered PNG dots, one colour per place type -- generated at
// 1x/2x/3x by scripts/gen-pin-assets.js (colours mirror src/lib/theme.ts).
//
// Why images instead of <View> children: iOS (Apple Maps) snapshots
// view-based marker children and drops them after the first frame, so the
// custom dots flashed once and then disappeared. An image is handed to the
// native annotation directly, which renders reliably on both platforms.
const PIN_IMAGES: Record<Place["type"], number> = {
  masjid: require("../../assets/pins/dot-masjid.png"),
  musalla: require("../../assets/pins/dot-musalla.png"),
  multi_faith_room: require("../../assets/pins/dot-multi-faith.png"),
};

// Cluster bubbles with the count BAKED INTO the image (one per bucket,
// generated by scripts/gen-cluster-assets.js). Live <View> bubbles crashed
// iOS: Apple Maps re-rasterizes view-based annotations continuously, and a
// few hundred of them churning through a zoom animation exhausts memory.
// Static images are owned by the native map and cost almost nothing.
const CLUSTER_IMAGES: Record<string, number> = {
  "2": require("../../assets/pins/cluster-2.png"),
  "3": require("../../assets/pins/cluster-3.png"),
  "4": require("../../assets/pins/cluster-4.png"),
  "5": require("../../assets/pins/cluster-5.png"),
  "6": require("../../assets/pins/cluster-6.png"),
  "7": require("../../assets/pins/cluster-7.png"),
  "8": require("../../assets/pins/cluster-8.png"),
  "9": require("../../assets/pins/cluster-9.png"),
  "10+": require("../../assets/pins/cluster-10p.png"),
  "20+": require("../../assets/pins/cluster-20p.png"),
  "30+": require("../../assets/pins/cluster-30p.png"),
  "50+": require("../../assets/pins/cluster-50p.png"),
  "100+": require("../../assets/pins/cluster-100p.png"),
  "200+": require("../../assets/pins/cluster-200p.png"),
  "500+": require("../../assets/pins/cluster-500p.png"),
};

type Props = {
  results: Array<{ place: Place; km: number }>;
  userLocation: { lat: number; lng: number } | null;
  /** When set (area search), the map animates to this point. */
  focus?: { lat: number; lng: number } | null;
  /** Increment to fly the map back to the user's location. */
  recenterNonce?: number;
  onSelect: (id: string) => void;
};

export default function PlacesMap({
  results,
  userLocation,
  focus,
  recenterNonce,
  onSelect,
}: Props) {
  const { scheme } = useTheme();
  const mapRef = useRef<MapView>(null);
  // Wherever the user has panned/zoomed to; null until the first gesture.
  const [region, setRegion] = useState<MapRegion | null>(null);

  // Computed ONCE, from a ref: MapView reads `initialRegion` on mount and
  // never again, and the effects below own the camera after that. As a
  // useMemo over [userLocation, results] this changed identity on every GPS
  // fix, which dragged the pin grouping below along with it.
  const initialRegionRef = useRef<MapRegion | null>(null);
  if (initialRegionRef.current === null) {
    const centre = userLocation
      ? { lat: userLocation.lat, lng: userLocation.lng }
      : results[0]
        ? { lat: results[0].place.lat, lng: results[0].place.lng }
        : { lat: FALLBACK_REGION.latitude, lng: FALLBACK_REGION.longitude };
    initialRegionRef.current = {
      latitude: centre.lat,
      longitude: centre.lng,
      latitudeDelta: 0.05,
      longitudeDelta: 0.05,
    };
  }
  const initialRegion = initialRegionRef.current;

  // Which viewport the pins are grouped for BEFORE the map reports one of
  // its own. It has to follow the first GPS fix rather than stay on the
  // mount-time fallback, because the effect below glides the camera to the
  // user and `onRegionChangeComplete` only lands when that animation ends —
  // without this, a cold start showed London's pins for the whole flight to
  // wherever the user actually is.
  //
  // Keyed on the coordinates, not the object, so a fresh fix at the same
  // place doesn't invalidate anything downstream.
  const fallbackRegion = useMemo<MapRegion>(
    () =>
      userLocation
        ? {
            latitude: userLocation.lat,
            longitude: userLocation.lng,
            latitudeDelta: 0.05,
            longitudeDelta: 0.05,
          }
        : initialRegion,
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [userLocation?.lat, userLocation?.lng, initialRegion],
  );

  // On the first GPS fix after mount, glide from the fallback view to the
  // user. initialRegion is only read once by the native map, so without this
  // the map stayed parked on central London forever when the fix arrived
  // after mount (i.e. on almost every cold start).
  const hadLocationAtMount = useRef(userLocation !== null);
  const centredOnUser = useRef(false);
  useEffect(() => {
    if (
      userLocation &&
      !hadLocationAtMount.current &&
      !centredOnUser.current &&
      !focus
    ) {
      centredOnUser.current = true;
      mapRef.current?.animateToRegion(
        {
          latitude: userLocation.lat,
          longitude: userLocation.lng,
          latitudeDelta: 0.05,
          longitudeDelta: 0.05,
        },
        600,
      );
    }
  }, [userLocation, focus]);

  // "Back to my location" button: fly home whenever the nonce ticks. A
  // nonce (not a boolean) so pressing the button twice in a row still works.
  const lastRecenter = useRef(recenterNonce ?? 0);
  useEffect(() => {
    const nonce = recenterNonce ?? 0;
    if (nonce === lastRecenter.current) return;
    // Only mark this nonce handled once there's a location to animate to —
    // a tap that arrives before the first GPS fix must still fire the
    // animation once userLocation lands and this effect re-runs, rather
    // than being marked "done" here and silently dropped.
    if (!userLocation) return;
    lastRecenter.current = nonce;
    mapRef.current?.animateToRegion(
      {
        latitude: userLocation.lat,
        longitude: userLocation.lng,
        latitudeDelta: 0.05,
        longitudeDelta: 0.05,
      },
      600,
    );
  }, [recenterNonce, userLocation]);

  // Fly to the searched area when one is chosen.
  useEffect(() => {
    if (focus) {
      mapRef.current?.animateToRegion(
        {
          latitude: focus.lat,
          longitude: focus.lng,
          latitudeDelta: 0.04,
          longitudeDelta: 0.04,
        },
        400,
      );
    }
  }, [focus]);

  // What the viewport renders: individual pins while under budget, numbered
  // cluster bubbles for dense areas when zoomed out — every place in view is
  // always represented (see src/lib/mapPins.ts).
  //
  // Note the `??` is resolved OUTSIDE the memo: once the map has reported a
  // region, `fallbackRegion` moving with the user must not re-run the
  // grouping, and it can't, because it is no longer part of the input.
  const groupingRegion = region ?? fallbackRegion;
  const { singles, clusters } = useMemo(
    () => buildPinGroups(results, groupingRegion),
    [results, groupingRegion],
  );

  // FIXED MARKER POOL. Exactly MAX_MARKERS Marker components mount once and
  // are never added or removed afterwards — react-native-maps 1.20's marker
  // add/remove path crashes iOS under the new architecture (expo/expo#40856,
  // react-native-maps#5217, seen on an iPhone XR in Expo Go every time
  // clustering swapped the marker set). Region changes only MOVE markers
  // and swap their images; unused slots hide at opacity 0.
  //
  // WHICH slot each place lands in is remembered between renders (see
  // assignSlots). Filling them in list order meant one place leaving the
  // viewport shifted every later place down a slot — and since tapping a
  // marker nudges the map to fit its callout, which fires a region change,
  // the callout you had just opened would re-label itself with a nearby
  // masjid's name while staying anchored over the dot you tapped.
  const assignment = useRef<Map<string, number>>(new Map());
  const slots = useMemo<Slot[]>(() => {
    const next = assignSlots({ singles, clusters }, assignment.current);
    assignment.current = next.assignment;
    return next.slots;
  }, [singles, clusters]);

  return (
    <MapView
      ref={mapRef}
      style={styles.map}
      initialRegion={initialRegion}
      onRegionChangeComplete={(r) => setRegion(r)}
      showsUserLocation={userLocation !== null}
      userInterfaceStyle={scheme}
      // BOTH branches must be a real, non-empty array, and never undefined or
      // null. MapView.java's setMapStyle is
      // `if (map != null && customMapStyleString != null)`, so a falsy style
      // is not "reset" — it is "do nothing", and the dark style stays applied
      // for the rest of the session. The library turns whatever it is handed
      // into JSON (`customMapStyle ? JSON.stringify(...) : undefined`), so the
      // light branch has to carry its own declarations to replace the dark
      // ones. (Apple Maps ignores this prop and follows userInterfaceStyle
      // above, which is why only Android was ever stuck.)
      customMapStyle={scheme === "dark" ? DARK_MAP_STYLE : NO_POI_STYLE}
      // Google Maps ships its own chrome, and all of it fought the app's --
      // on Android only, which is exactly the sort of divergence that goes
      // unnoticed when testing on an iPhone. All three are inert on Apple
      // Maps, so no Platform branch is needed.
      //
      // toolbarEnabled: pops two Google buttons over the bottom sheet on
      //   every pin tap.
      // showsMyLocationButton: a second "my location" FAB that lands under
      //   the search row and duplicates the app's own recenter control.
      // moveOnMarkerPress: nudges the camera on every pin tap, which fires
      //   onRegionChangeComplete and re-runs the pin grouping -- the exact
      //   callout churn the fixed slot pool above exists to avoid.
      toolbarEnabled={false}
      showsMyLocationButton={false}
      moveOnMarkerPress={false}
    >
      {slots.map((slot, index) => {
        if (slot?.kind === "cluster") {
          const { cluster } = slot;
          return (
            <Marker
              key={`slot-${index}`}
              coordinate={{ latitude: cluster.lat, longitude: cluster.lng }}
              opacity={1}
              anchor={{ x: 0.5, y: 0.5 }}
              image={CLUSTER_IMAGES[cluster.bucket]}
              tracksViewChanges={false}
              // Tap = zoom into the cluster's cell; the closer view either
              // resolves it into pins or into smaller clusters.
              onPress={() =>
                mapRef.current?.animateToRegion(
                  {
                    latitude: cluster.lat,
                    longitude: cluster.lng,
                    latitudeDelta: cluster.latitudeDelta,
                    longitudeDelta: cluster.longitudeDelta,
                  },
                  350,
                )
              }
              accessibilityLabel={`${cluster.count} places — tap to zoom in`}
            />
          );
        }
        if (slot) {
          const { place, km } = slot.candidate;
          return (
            <Marker
              key={`slot-${index}`}
              coordinate={{ latitude: place.lat, longitude: place.lng }}
              opacity={1}
              title={place.name}
              // Type + distance in the callout, so "is it walkable?" is
              // answered without leaving the map.
              description={`${PLACE_TYPE_LABELS[place.type]} · ${formatDistance(km)}`}
              onCalloutPress={() => onSelect(place.id)}
              image={PIN_IMAGES[place.type]}
              // Centre the dot on the coordinate (Android; iOS centres by
              // default).
              anchor={{ x: 0.5, y: 0.5 }}
              tracksViewChanges={false}
            />
          );
        }
        return (
          <Marker
            key={`slot-${index}`}
            coordinate={HIDDEN_COORDINATE}
            opacity={0}
            anchor={{ x: 0.5, y: 0.5 }}
            image={PIN_IMAGES.masjid}
            tracksViewChanges={false}
            // opacity: 0 removes a view from SIGHT, not from the
            // accessibility tree. Apple Maps annotation views are
            // accessibility elements by default, so in a sparse viewport
            // VoiceOver had up to 278 unlabelled parked pins to swipe past
            // before reaching anything real. `accessible` is the prop that
            // does the work; importantForAccessibility is the Android twin.
            accessible={false}
            importantForAccessibility="no"
          />
        );
      })}
    </MapView>
  );
}

const styles = StyleSheet.create({
  map: {
    flex: 1,
  },
});
