import React, { useEffect, useMemo, useRef, useState } from "react";
import { StyleSheet } from "react-native";
import MapView, { Marker } from "react-native-maps";

import { PLACE_TYPE_LABELS, Place } from "@/data/places";
import { useTheme } from "@/context/ThemeContext";
import { formatDistance } from "@/lib/distance";
import { buildPinGroups, type MapRegion } from "@/lib/mapPins";

// Google Maps (Android) needs an explicit style array for dark mode; Apple
// Maps (iOS) follows the userInterfaceStyle prop instead and ignores this.
const DARK_MAP_STYLE = [
  { elementType: "geometry", stylers: [{ color: "#242f3e" }] },
  { elementType: "labels.text.fill", stylers: [{ color: "#8f9bab" }] },
  { elementType: "labels.text.stroke", stylers: [{ color: "#242f3e" }] },
  {
    featureType: "poi",
    elementType: "labels.text.fill",
    stylers: [{ color: "#93817c" }],
  },
  {
    featureType: "road",
    elementType: "geometry",
    stylers: [{ color: "#38414e" }],
  },
  {
    featureType: "road",
    elementType: "geometry.stroke",
    stylers: [{ color: "#212a37" }],
  },
  {
    featureType: "road",
    elementType: "labels.text.fill",
    stylers: [{ color: "#9ca5b3" }],
  },
  {
    featureType: "transit",
    elementType: "geometry",
    stylers: [{ color: "#2f3948" }],
  },
  {
    featureType: "water",
    elementType: "geometry",
    stylers: [{ color: "#17263c" }],
  },
];

const FALLBACK_REGION = {
  latitude: 51.5074,
  longitude: -0.1278,
  latitudeDelta: 0.05,
  longitudeDelta: 0.05,
};

// Small pre-rendered PNG dots, one colour per place type -- generated at
// 1x/2x/3x by scripts/gen-pin-assets.js (colours mirror src/lib/theme.ts).
//
// Why images instead of <View> children: iOS (Apple Maps) snapshots
// view-based marker children and drops them after the first frame, so the
// custom dots flashed once and then disappeared. An image is handed to the
// native annotation directly, which renders reliably on both platforms.
const PIN_IMAGES: Record<Place["type"], number> = {
  masjid: require("../../assets/pins/dot-masjid.png"),
  musalla: require("../../assets/pins/dot-musalla.png"),
  multi_faith_room: require("../../assets/pins/dot-multi-faith.png"),
};

// Cluster bubbles with the count BAKED INTO the image (one per bucket,
// generated by scripts/gen-cluster-assets.js). Live <View> bubbles crashed
// iOS: Apple Maps re-rasterizes view-based annotations continuously, and a
// few hundred of them churning through a zoom animation exhausts memory.
// Static images are owned by the native map and cost almost nothing.
const CLUSTER_IMAGES: Record<string, number> = {
  "2": require("../../assets/pins/cluster-2.png"),
  "3": require("../../assets/pins/cluster-3.png"),
  "4": require("../../assets/pins/cluster-4.png"),
  "5": require("../../assets/pins/cluster-5.png"),
  "6": require("../../assets/pins/cluster-6.png"),
  "7": require("../../assets/pins/cluster-7.png"),
  "8": require("../../assets/pins/cluster-8.png"),
  "9": require("../../assets/pins/cluster-9.png"),
  "10+": require("../../assets/pins/cluster-10p.png"),
  "20+": require("../../assets/pins/cluster-20p.png"),
  "30+": require("../../assets/pins/cluster-30p.png"),
  "50+": require("../../assets/pins/cluster-50p.png"),
  "100+": require("../../assets/pins/cluster-100p.png"),
  "200+": require("../../assets/pins/cluster-200p.png"),
  "500+": require("../../assets/pins/cluster-500p.png"),
};

type Props = {
  results: Array<{ place: Place; km: number }>;
  userLocation: { lat: number; lng: number } | null;
  /** When set (area search), the map animates to this point. */
  focus?: { lat: number; lng: number } | null;
  /** Increment to fly the map back to the user's location. */
  recenterNonce?: number;
  onSelect: (id: string) => void;
};

export default function PlacesMap({
  results,
  userLocation,
  focus,
  recenterNonce,
  onSelect,
}: Props) {
  const { scheme } = useTheme();
  const mapRef = useRef<MapView>(null);
  // Wherever the user has panned/zoomed to; null until the first gesture.
  const [region, setRegion] = useState<MapRegion | null>(null);

  const initialRegion = useMemo(() => {
    const centre = userLocation
      ? { lat: userLocation.lat, lng: userLocation.lng }
      : results[0]
        ? { lat: results[0].place.lat, lng: results[0].place.lng }
        : { lat: FALLBACK_REGION.latitude, lng: FALLBACK_REGION.longitude };

    return {
      latitude: centre.lat,
      longitude: centre.lng,
      latitudeDelta: 0.05,
      longitudeDelta: 0.05,
    };
  }, [userLocation, results]);

  // On the first GPS fix after mount, glide from the fallback view to the
  // user. initialRegion is only read once by the native map, so without this
  // the map stayed parked on central London forever when the fix arrived
  // after mount (i.e. on almost every cold start).
  const hadLocationAtMount = useRef(userLocation !== null);
  const centredOnUser = useRef(false);
  useEffect(() => {
    if (
      userLocation &&
      !hadLocationAtMount.current &&
      !centredOnUser.current &&
      !focus
    ) {
      centredOnUser.current = true;
      mapRef.current?.animateToRegion(
        {
          latitude: userLocation.lat,
          longitude: userLocation.lng,
          latitudeDelta: 0.05,
          longitudeDelta: 0.05,
        },
        600,
      );
    }
  }, [userLocation, focus]);

  // "Back to my location" button: fly home whenever the nonce ticks. A
  // nonce (not a boolean) so pressing the button twice in a row still works.
  const lastRecenter = useRef(recenterNonce ?? 0);
  useEffect(() => {
    const nonce = recenterNonce ?? 0;
    if (nonce === lastRecenter.current) return;
    lastRecenter.current = nonce;
    if (!userLocation) return;
    mapRef.current?.animateToRegion(
      {
        latitude: userLocation.lat,
        longitude: userLocation.lng,
        latitudeDelta: 0.05,
        longitudeDelta: 0.05,
      },
      600,
    );
  }, [recenterNonce, userLocation]);

  // Fly to the searched area when one is chosen.
  useEffect(() => {
    if (focus) {
      mapRef.current?.animateToRegion(
        {
          latitude: focus.lat,
          longitude: focus.lng,
          latitudeDelta: 0.04,
          longitudeDelta: 0.04,
        },
        400,
      );
    }
  }, [focus]);

  // What the viewport renders: individual pins while under budget, numbered
  // cluster bubbles for dense areas when zoomed out — every place in view is
  // always represented (see src/lib/mapPins.ts).
  const { singles, clusters } = useMemo(
    () => buildPinGroups(results, region ?? initialRegion),
    [results, region, initialRegion],
  );

  return (
    <MapView
      ref={mapRef}
      style={styles.map}
      initialRegion={initialRegion}
      onRegionChangeComplete={(r) => setRegion(r)}
      showsUserLocation={userLocation !== null}
      userInterfaceStyle={scheme}
      customMapStyle={scheme === "dark" ? DARK_MAP_STYLE : undefined}
    >
      {clusters.map((cluster) => (
        <Marker
          key={cluster.key}
          coordinate={{ latitude: cluster.lat, longitude: cluster.lng }}
          anchor={{ x: 0.5, y: 0.5 }}
          image={CLUSTER_IMAGES[cluster.bucket]}
          // Static image marker: never re-rasterizes (see CLUSTER_IMAGES).
          tracksViewChanges={false}
          // Tap = zoom into the cluster's cell; the closer view either
          // resolves it into pins or into smaller clusters.
          onPress={() =>
            mapRef.current?.animateToRegion(
              {
                latitude: cluster.lat,
                longitude: cluster.lng,
                latitudeDelta: cluster.latitudeDelta,
                longitudeDelta: cluster.longitudeDelta,
              },
              350,
            )
          }
          accessibilityLabel={`${cluster.count} places — tap to zoom in`}
        />
      ))}
      {singles.map(({ place, km }) => (
        <Marker
          key={place.id}
          coordinate={{ latitude: place.lat, longitude: place.lng }}
          title={place.name}
          // Type + distance in the callout, so "is it walkable?" is answered
          // without leaving the map.
          description={`${PLACE_TYPE_LABELS[place.type]} · ${formatDistance(km)}`}
          onCalloutPress={() => onSelect(place.id)}
          image={PIN_IMAGES[place.type]}
          // Centre the dot on the coordinate (Android; iOS centres by default).
          anchor={{ x: 0.5, y: 0.5 }}
          // Static markers with no view children: never re-rasterize.
          tracksViewChanges={false}
        />
      ))}
    </MapView>
  );
}

const styles = StyleSheet.create({
  map: {
    flex: 1,
  },
});
