-- Seed bundled PLACES into Supabase (run once after creating tables).
-- Safe to re-run: deletes existing rows with matching ids first.

DELETE FROM places WHERE id IN (
  'east-london-mosque',
  'london-central-mosque',
  'brick-lane-jamme-masjid',
  'al-manaar',
  'finsbury-park-mosque',
  'lewisham-islamic-centre',
  'croydon-mosque',
  'ucl-prayer-room',
  'guys-hospital-multifaith',
  'st-thomas-multifaith',
  'westfield-stratford-prayer-room',
  'canary-wharf-multifaith'
);

INSERT INTO places (
  id, name, type, address, lat, lng, facilities,
  jumuah_times, jamaat, notes, last_verified, source,
  phone, website, facebook, instagram, confidence
) VALUES
(
  'east-london-mosque',
  'East London Mosque & London Muslim Centre',
  'masjid',
  '82-92 Whitechapel Rd, London E1 1JQ',
  51.5169,
  -0.0655,
  '{"sistersSpace":true,"wudu":true,"disabledAccess":true,"parking":true,"jumuah":true,"janazah":true}'::jsonb,
  '["13:15","14:15"]'::jsonb,
  '{"fajr":"05:15","dhuhr":"13:15","asr":"17:45","maghrib":"21:10","isha":"22:30","source":"Sample data — replace with real timetable","recordedOn":"2026-07-23"}'::jsonb,
  'One of the largest mosques in the UK. Sisters'' entrance via the London Muslim Centre.',
  '2026-07-01',
  'Sample data — verify via eastlondonmosque.org.uk',
  '020 7650 3000',
  'https://www.eastlondonmosque.org.uk/',
  NULL,
  NULL,
  'unverified'
),
(
  'london-central-mosque',
  'London Central Mosque (Regent''s Park)',
  'masjid',
  '146 Park Rd, London NW8 7RG',
  51.5289,
  -0.1647,
  '{"sistersSpace":true,"wudu":true,"disabledAccess":true,"parking":true,"jumuah":true,"janazah":true}'::jsonb,
  '["13:30"]'::jsonb,
  NULL,
  NULL,
  '2026-06-20',
  'Sample data — verify via iccuk.org',
  '020 7724 3363',
  'https://www.iccuk.org/',
  NULL,
  NULL,
  'unverified'
),
(
  'brick-lane-jamme-masjid',
  'Brick Lane Jamme Masjid',
  'masjid',
  '59 Brick Ln, London E1 6QL',
  51.5195,
  -0.0717,
  '{"sistersSpace":false,"wudu":true,"disabledAccess":false,"parking":false,"jumuah":true,"janazah":false}'::jsonb,
  '["13:30"]'::jsonb,
  NULL,
  NULL,
  '2026-05-14',
  'Sample data',
  NULL,
  NULL,
  NULL,
  NULL,
  'unverified'
),
(
  'al-manaar',
  'Al-Manaar (Muslim Cultural Heritage Centre)',
  'masjid',
  '244 Acklam Rd, London W10 5YG',
  51.5208,
  -0.2049,
  '{"sistersSpace":true,"wudu":true,"disabledAccess":true,"parking":false,"jumuah":true,"janazah":true}'::jsonb,
  '["13:30"]'::jsonb,
  NULL,
  NULL,
  '2026-04-02',
  'Sample data',
  NULL,
  NULL,
  NULL,
  NULL,
  'unverified'
),
(
  'finsbury-park-mosque',
  'Finsbury Park Mosque',
  'masjid',
  '7-11 St Thomas''s Rd, London N4 2QH',
  51.5645,
  -0.1069,
  '{"sistersSpace":true,"wudu":true,"disabledAccess":true,"parking":false,"jumuah":true,"janazah":false}'::jsonb,
  '["13:15"]'::jsonb,
  NULL,
  NULL,
  '2026-03-19',
  'Sample data',
  NULL,
  NULL,
  NULL,
  NULL,
  'unverified'
),
(
  'lewisham-islamic-centre',
  'Lewisham Islamic Centre',
  'masjid',
  '363-365 Lewisham High St, London SE13 6NZ',
  51.4507,
  -0.0163,
  '{"sistersSpace":true,"wudu":true,"disabledAccess":true,"parking":true,"jumuah":true,"janazah":true}'::jsonb,
  '["13:05","14:00"]'::jsonb,
  '{"fajr":"05:10","dhuhr":"13:05","asr":"17:40","maghrib":"21:08","isha":"22:25","source":"Sample data — replace with real timetable","recordedOn":"2026-07-23"}'::jsonb,
  NULL,
  '2026-06-11',
  'Sample data',
  NULL,
  NULL,
  NULL,
  NULL,
  'unverified'
),
(
  'croydon-mosque',
  'Croydon Mosque & Islamic Centre',
  'masjid',
  '525 London Rd, Thornton Heath CR7 6AR',
  51.3937,
  -0.1049,
  '{"sistersSpace":true,"wudu":true,"disabledAccess":true,"parking":true,"jumuah":true,"janazah":true}'::jsonb,
  '["13:30"]'::jsonb,
  NULL,
  NULL,
  '2026-02-27',
  'Sample data',
  NULL,
  NULL,
  NULL,
  NULL,
  'unverified'
),
(
  'ucl-prayer-room',
  'UCL Prayer Room (Student Central)',
  'musalla',
  'Malet St, London WC1E 7HY',
  51.5223,
  -0.1301,
  '{"sistersSpace":true,"wudu":true,"disabledAccess":true,"parking":false,"jumuah":true,"janazah":false}'::jsonb,
  '["13:15"]'::jsonb,
  NULL,
  'Term-time access may require a student card. Jumu''ah run by the ISoc.',
  '2026-01-30',
  'Sample data — verify with UCL ISoc',
  NULL,
  NULL,
  NULL,
  NULL,
  'unverified'
),
(
  'guys-hospital-multifaith',
  'Guy''s Hospital Multi-faith Chaplaincy',
  'multi_faith_room',
  'Great Maze Pond, London SE1 9RT',
  51.5033,
  -0.0876,
  '{"sistersSpace":false,"wudu":true,"disabledAccess":true,"parking":false,"jumuah":true,"janazah":false}'::jsonb,
  '["13:00"]'::jsonb,
  NULL,
  'Open to patients, visitors and staff. Ask at main reception for directions.',
  '2026-07-05',
  'Sample data — verify with GSTT chaplaincy',
  NULL,
  NULL,
  NULL,
  NULL,
  'unverified'
),
(
  'st-thomas-multifaith',
  'St Thomas'' Hospital Multi-faith Room',
  'multi_faith_room',
  'Westminster Bridge Rd, London SE1 7EH',
  51.4986,
  -0.1177,
  '{"sistersSpace":false,"wudu":true,"disabledAccess":true,"parking":false,"jumuah":false,"janazah":false}'::jsonb,
  NULL,
  NULL,
  'Quiet room available 24/7. Wudu facilities nearby.',
  '2026-07-05',
  'Sample data — verify with GSTT chaplaincy',
  NULL,
  NULL,
  NULL,
  NULL,
  'unverified'
),
(
  'westfield-stratford-prayer-room',
  'Westfield Stratford City Prayer Room',
  'musalla',
  'Montfichet Rd, London E20 1EJ',
  51.5423,
  -0.0064,
  '{"sistersSpace":true,"wudu":true,"disabledAccess":true,"parking":true,"jumuah":false,"janazah":false}'::jsonb,
  NULL,
  NULL,
  'Located near the Chestnut Plaza entrance. Ask guest services if unsure.',
  '2025-12-10',
  'Sample data',
  NULL,
  NULL,
  NULL,
  NULL,
  'unverified'
),
(
  'canary-wharf-multifaith',
  'Canary Wharf Multi-faith Prayer Room',
  'multi_faith_room',
  'Jubilee Place, London E14 5NY',
  51.5036,
  -0.0184,
  '{"sistersSpace":true,"wudu":true,"disabledAccess":true,"parking":false,"jumuah":true,"janazah":false}'::jsonb,
  '["13:10"]'::jsonb,
  NULL,
  NULL,
  '2026-05-22',
  'Sample data',
  NULL,
  NULL,
  NULL,
  NULL,
  'unverified'
);
